server:
  port: 8082
  servlet:
    context-path: /account-processing/api/v1/

spring:
  application:
    name: account-processing
  datasource:
    url: jdbc:postgresql://localhost:5433/account_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    topics:
      client-products: client_products
      client-cards: client_cards
      client-transactions: client_transactions
      client-payments: client_payments
      service-logs: service_logs
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-processing-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
      enable-idempotence: true
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
      retry-backoff-ms: 1000
      compression-type: snappy

transaction:
  limits:
    max-transactions: 10
    time-window-minutes: 60

account-processing:
  kafka:
    consumer:
      enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    org.example.accountprocessing: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE