server:
  port: 8081
  servlet:
    context-path: /client-processing/api/v1

spring:
  application:
    name: client-processing
  datasource:
    url: jdbc:postgresql://localhost:5433/client_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    topics:
      client-products: client_products
      client-credit-products: client_credit_products
      client-cards: client_cards
      service-logs: service_logs
    bootstrap-servers: localhost:9092
    consumer:
      group-id: client-processing-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
      enable-idempotence: true
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
      retry-backoff-ms: 1000
      compression-type: snappy

client-processing:
  kafka:
    producer:
      enable: true
  metric:
    execution-time-limit-ms: 1

caching:
  enabled: true
  default-ttl-seconds: 300
  cleanup-interval-seconds: 60


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    org.example.clientprocessing: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE