server:
  port: 8083
  servlet:
    context-path: /credit-processing/api/v1

spring:
  application:
    name: credit-processing
  datasource:
    url: jdbc:postgresql://localhost:5433/credit_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    org.example.creditprocessing: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE